//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchActually_TechnicalAssignment.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public long HotelID { get; set; }
        public string HotelName { get; set; }
        public Nullable<int> HotelCountry { get; set; }
        public Nullable<int> HotelCity { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
        public string HotelAddress { get; set; }
        public string StarRatings { get; set; }
        public string HotelWebsite { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
